// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Get() {
  return window['go']['userconfig']['ConfigStore']['Get']();
}

export function Save(arg1) {
  return window['go']['userconfig']['ConfigStore']['Save'](arg1);
}
