// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {userconfig} from '../models';

export function Get():Promise<userconfig.Config>;

export function Save(arg1:userconfig.Config):Promise<void>;
