// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {userconfig} from '../models';
import {scraping} from '../models';

export function ChooseDirectory():Promise<string>;

export function GetConfig(arg1:userconfig.ConfigStore):Promise<userconfig.Config>;

export function GetGameCoverUrl(arg1:scraping.Rom):Promise<string>;

export function GetGamesByName(arg1:string):Promise<Array<scraping.Rom>>;

export function NewConfigStore():Promise<userconfig.ConfigStore>;

export function PlatformToString(arg1:scraping.Platform):Promise<string>;

export function RAvalidateHash(arg1:scraping.Rom):Promise<boolean>;

export function VimDownloadGame(arg1:scraping.Rom,arg2:string):Promise<void>;

export function VimSearchGames(arg1:string,arg2:string):Promise<Array<scraping.Rom>>;
