// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseDirectory() {
  return window['go']['main']['App']['ChooseDirectory']();
}

export function GetGameCoverUrl(arg1) {
  return window['go']['main']['App']['GetGameCoverUrl'](arg1);
}

export function GetGamesByName(arg1) {
  return window['go']['main']['App']['GetGamesByName'](arg1);
}

export function PlatformToString(arg1) {
  return window['go']['main']['App']['PlatformToString'](arg1);
}

export function RAvalidateHash(arg1) {
  return window['go']['main']['App']['RAvalidateHash'](arg1);
}

export function VimDownloadGame(arg1, arg2) {
  return window['go']['main']['App']['VimDownloadGame'](arg1, arg2);
}

export function VimSearchGames(arg1, arg2) {
  return window['go']['main']['App']['VimSearchGames'](arg1, arg2);
}
